region        = "ap-southeast-1"
ec2_security_group_name = "docker-demo_sg"
ec2_security_group_description = "Allow traffic for docker app and ssh"
ec2_instance_type = "t3.small"
keypair_name = "viettq12-keypair"
